const URL='https://tmxpueakxibsaakdyusn.supabase.co',KEY='sb_publishable_8sCgnOXk3XuRE28Qmk_ekg_9VSS4ASZ',LOCAL='dinnerDecision.v3',AUTH_STORE='dinnerSupabaseAuth.v1';
const DEFAULTS=[['烧烤','🍖'],['火锅','🍲'],['炒菜','🥘'],['粤菜','🥢'],['日料','🍣'],['韩餐','🍱'],['小龙虾','🦞'],['面馆','🍜']],$=id=>document.getElementById(id);
let cloud=false,session=null,groupId=null,groupName='',myName='',members=[],historyLimit=20,deleteTarget=null,clearActive=false,holdStart=0,holdRaf=0,syncTimer=0,syncBusy=false;
const state={mode:'fair',sound:true,candidates:[],history:[],weightHistory:[],finalists:[],result:null,rejectCount:0,regretUsed:false};
const uid=()=>crypto?.randomUUID?.()||'c_'+Date.now().toString(36)+Math.random().toString(36).slice(2),today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function loadLocal(){try{const s=JSON.parse(localStorage.getItem(LOCAL)||localStorage.getItem('dinnerDecision.v2')||'{}');state.mode=s.mode==='smart'?'smart':'fair';state.sound=s.sound!==false;state.candidates=Array.isArray(s.candidates)&&s.candidates.length?s.candidates.map(x=>({id:String(x.id||uid()),name:String(x.name).slice(0,30),emoji:String(x.emoji||'🍽️'),enabled:x.enabled!==false})):DEFAULTS.map(([name,emoji])=>({id:uid(),name,emoji,enabled:true}));state.history=Array.isArray(s.history)?s.history:[];state.weightHistory=state.history.slice(0,50)}catch{state.candidates=DEFAULTS.map(([name,emoji])=>({id:uid(),name,emoji,enabled:true}))}}
function saveLocal(){if(!cloud)localStorage.setItem(LOCAL,JSON.stringify({mode:state.mode,sound:state.sound,candidates:state.candidates,history:state.history.slice(0,200)}))}
function toast(t,ms=1500){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.remove('show'),ms)}
function tone(f=520){if(!state.sound)return;try{const C=window.AudioContext||window.webkitAudioContext,c=tone.c||(tone.c=new C()),o=c.createOscillator(),g=c.createGain();o.frequency.value=f;g.gain.setValueAtTime(.02,c.currentTime);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.05);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.05)}catch{}}
const enabled=()=>state.candidates.filter(x=>x.enabled),memberName=id=>members.find(x=>x.user_id===id)?.display_name||'成员';
function daysAgo(ymd){const d=new Date(ymd+'T00:00:00'),n=new Date();return Math.floor((new Date(n.getFullYear(),n.getMonth(),n.getDate())-d)/86400000)}
function factor(id){if(state.mode!=='smart')return 1;const rows=state.weightHistory.filter(h=>h.candidate_id===id);if(!rows.length)return 1;const d=Math.max(0,daysAgo(rows[0].meal_date));let f=d<=1?.25:d<=3?.4:d<=7?.65:d<=14?.85:1;return Math.max(.12,f*Math.pow(.9,Math.max(0,rows.filter(h=>daysAgo(h.meal_date)<=14).length-1)))}
function pick(arr){if(state.mode==='fair')return arr[Math.floor(Math.random()*arr.length)];const w=arr.map(x=>factor(x.id)),sum=w.reduce((a,b)=>a+b,0);let r=Math.random()*sum;for(let i=0;i<arr.length;i++){r-=w[i];if(r<=0)return arr[i]}return arr.at(-1)}
function pick3(arr){const p=[...arr],o=[];while(p.length&&o.length<3){const x=pick(p);o.push(x);p.splice(p.findIndex(y=>y.id===x.id),1)}return o}
function renderSync(){$('syncDot').classList.toggle('online',cloud);$('syncTitle').textContent=cloud?`${groupName} · 多人同步`:'单机模式';$('syncSub').textContent=cloud?`${members.length}人共享 · 当前：${myName} · 自动同步`:'数据仅保存在当前浏览器';$('syncActionBtn').textContent=cloud?'账户':'登录共享';$('accountBtn').textContent=cloud?myName:'登录同步'}
function renderMode(){$('fairBtn').classList.toggle('active',state.mode==='fair');$('smartBtn').classList.toggle('active',state.mode==='smart');$('modeDesc').textContent=state.mode==='fair'?'每个候选完全等概率':'根据仍存在的共享最近历史自动降权'}
function renderCandidates(){const a=enabled();$('candidateCount').textContent=`当前候选 ${a.length} 项${cloud?' · 已同步':''}`;$('drawThreeBtn').disabled=a.length<3;$('candidateTags').replaceChildren();a.slice(0,12).forEach(x=>{const s=document.createElement('span');s.className='tag';s.textContent=`${x.emoji} ${x.name}`;$('candidateTags').append(s)})}
function renderManager(){$('candidateList').replaceChildren();state.candidates.forEach(x=>{const r=document.createElement('div');r.className='candidate-row';const c=document.createElement('input');c.type='checkbox';c.checked=x.enabled;c.onchange=async()=>{if(!c.checked&&enabled().length<=3){c.checked=true;return toast('至少保留 3 个候选')}await setEnabled(x,c.checked)};const n=document.createElement('div');n.className='candidate-name';n.textContent=`${x.emoji} ${x.name}`;const d=document.createElement('button');d.type='button';d.className='danger';d.textContent='删除';d.onclick=async()=>{if(state.candidates.length<=3)return toast('至少保留 3 个候选');if(confirm(`删除候选「${x.name}」？历史快照会保留。`))await delCandidate(x)};r.append(c,n,d);$('candidateList').append(r)})}
function htext(h){const d=new Intl.DateTimeFormat('zh-CN',{month:'numeric',day:'numeric',weekday:'short'}).format(new Date(h.meal_date+'T00:00:00'));return `${d} · ${h.meal_period||'晚餐'}`}
function renderHistory(){$('historyList').replaceChildren();if(!state.history.length){const e=document.createElement('div');e.className='empty';e.textContent=cloud?'共享历史还为空，记录第一顿吧。':'还没有历史记录';$('historyList').append(e);$('loadMoreBtn').classList.add('hidden');return}$('loadMoreBtn').classList.toggle('hidden',state.history.length<historyLimit);state.history.forEach(h=>{const a=document.createElement('article');a.className='history-item';const m=document.createElement('div');m.className='history-main';const e=document.createElement('div');e.className='emoji';e.textContent=h.emoji_snapshot||h.emoji||'🍽️';const r=document.createElement('div');const n=document.createElement('div');n.className='history-name';n.textContent=h.candidate_name_snapshot||h.name;const meta=document.createElement('div');meta.className='history-meta';meta.textContent=htext(h)+(cloud?` · 记录人：${memberName(h.created_by)}`:'');r.append(n,meta);m.append(e,r);a.append(m);if(h.note){const note=document.createElement('div');note.className='history-note';note.textContent=h.note;a.append(note)}const del=document.createElement('button');del.type='button';del.className='trash';del.textContent='🗑';del.onclick=()=>openDelete(h);a.append(del);$('historyList').append(a)})}
function renderJaw(){$('jawCount').textContent=`${state.rejectCount} 次否决`;$('jawFill').style.width=Math.min(100,state.rejectCount*34)+'%';$('jawMessage').textContent=state.rejectCount===0?'目前看起来还挺随和。':state.rejectCount===1?'开始有点挑了。':state.rejectCount===2?'命运已经感受到压力。':'你不是不知道吃什么，你只是在等我说出你想吃的那个 😂'}
function renderFinal(active=''){$('finalGrid').replaceChildren();state.finalists.forEach(x=>{const d=document.createElement('div');d.className='final-card'+(x.id===active?' active':'');d.innerHTML=`<div style="font-size:27px">${x.emoji}</div><b></b>`;d.querySelector('b').textContent=x.name;$('finalGrid').append(d)})}
async function animate(arr,dur=1100){return new Promise(ok=>{let t=0,i=0,delay=65;$('reel').classList.add('rolling');function step(){const x=arr[i%arr.length];$('reelIcon').textContent=x.emoji;$('reelName').textContent=x.name;$('reelSub').textContent='命运正在替你筛选……';tone(430+(i%5)*25);i++;t+=delay;if(t>=dur){$('reel').classList.remove('rolling');return ok()}delay=Math.min(170,delay*1.08);setTimeout(step,delay)}step()})}
async function draw3(replace=false){const a=enabled();if(a.length<3)return toast('至少启用 3 个候选');if(replace)reject();else{state.rejectCount=0;state.regretUsed=false;renderJaw()}await animate(a);state.finalists=pick3(a);renderFinal();$('reelIcon').textContent='🏁';$('reelName').textContent='三位选手已就位';$('reelSub').textContent='进入三选一决赛';$('finalistsPanel').classList.remove('hidden');$('resultPanel').classList.add('hidden')}
async function final(regret=false){let t=0,i=0,delay=75;await new Promise(ok=>{function step(){const x=state.finalists[i%3];renderFinal(x.id);tone(470+(i%5)*28);i++;t+=delay;if(t>=1450)return ok();delay=Math.min(190,delay*1.1);setTimeout(step,delay)}step()});const pool=regret&&state.result?state.finalists.filter(x=>x.id!==state.result.id):state.finalists;state.result=pick(pool);renderFinal(state.result.id);$('resultEmoji').textContent=state.result.emoji;$('resultName').textContent=state.result.name;$('resultPanel').classList.remove('hidden');$('resultCopy').textContent=state.regretUsed?'命运已经给了第二次答案。':'今晚就它了。';$('regretBtn').classList.toggle('hidden',state.regretUsed);$('lockedText').classList.toggle('hidden',!state.regretUsed)}
function reject(){state.rejectCount++;renderJaw();const m=['看来你还有一点自己的想法。','又不要？命运开始怀疑自己了。','你不是不知道吃什么，你只是在等我说出你想吃的那个 😂'];toast(m[Math.min(state.rejectCount-1,2)],1700)}
async function regret(){if(state.regretUsed)return toast('这次不许反悔了 😏');reject();state.regretUsed=true;await final(true)}
const open=id=>$(id).classList.remove('hidden'),close=id=>$(id).classList.add('hidden');document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>close(b.dataset.close));document.querySelectorAll('.overlay').forEach(o=>o.onclick=e=>{if(e.target===o)close(o.id)});
function openRecord(id=''){const s=$('recordCandidate');s.replaceChildren();state.candidates.forEach(x=>{const o=document.createElement('option');o.value=x.id;o.textContent=`${x.emoji} ${x.name}`;o.selected=x.id===id;s.append(o)});$('recordDate').value=today();$('recordPeriod').value='晚餐';$('recordNote').value='';$('noteCount').textContent='0/500';open('recordOverlay')}
function openDelete(h){deleteTarget=h;$('deletePreview').textContent=`${htext(h)} · ${h.candidate_name_snapshot||h.name}${h.note?'\n备注：'+h.note:''}`;open('deleteOverlay')}
function saveAuth(){try{session?localStorage.setItem(AUTH_STORE,JSON.stringify(session)):localStorage.removeItem(AUTH_STORE)}catch{}}
function readAuth(){try{return JSON.parse(localStorage.getItem(AUTH_STORE)||'null')}catch{return null}}
function authHeaders(extra={}){return {'apikey':KEY,'Authorization':`Bearer ${session?.access_token||KEY}`,...extra}}
async function authRequest(path,{method='POST',body}={}){const r=await fetch(URL+path,{method,headers:{'apikey':KEY,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data?.msg||data?.message||data?.error_description||`HTTP ${r.status}`);return data}
async function refreshAuth(){if(!session?.refresh_token)return false;try{const data=await authRequest('/auth/v1/token?grant_type=refresh_token',{body:{refresh_token:session.refresh_token}});session=data;saveAuth();return true}catch{session=null;saveAuth();return false}}
async function ensureAuth(){if(!session)return false;const exp=Number(session.expires_at||0);if(exp&&exp-Date.now()/1000<60)return refreshAuth();return true}
async function rest(path,{method='GET',body=null,prefer='',retry=true}={}){if(!(await ensureAuth()))throw new Error('登录已失效，请重新登录');const headers=authHeaders({'Content-Type':'application/json'});if(prefer)headers.Prefer=prefer;const r=await fetch(URL+'/rest/v1/'+path,{method,headers,body:body==null?undefined:JSON.stringify(body)});if(r.status===401&&retry&&await refreshAuth())return rest(path,{method,body,prefer,retry:false});const text=await r.text();let data=null;if(text)try{data=JSON.parse(text)}catch{data=text}if(!r.ok)throw new Error(data?.message||data?.hint||`HTTP ${r.status}`);return data}
const q=v=>encodeURIComponent(v);
async function saveRecord(){const c=state.candidates.find(x=>x.id===$('recordCandidate').value);if(!c)return toast('请选择吃了什么');const base={candidate_id:c.id,candidate_name_snapshot:c.name,emoji_snapshot:c.emoji,meal_date:$('recordDate').value||today(),meal_period:$('recordPeriod').value,note:$('recordNote').value.trim()};try{if(cloud){await rest('dinner_history',{method:'POST',body:{...base,group_id:groupId,created_by:session.user.id},prefer:'return=minimal'});await loadHistory()}else{const local={...base,id:uid(),name:c.name,emoji:c.emoji,created_at:new Date().toISOString()};state.history.unshift(local);state.weightHistory=state.history.slice(0,50);saveLocal();renderHistory()}close('recordOverlay');toast('已记录这顿饭')}catch(e){toast('保存失败：'+e.message,2600)}}
async function deleteHistory(){if(!deleteTarget)return;try{if(cloud){await rest(`dinner_history?id=eq.${q(deleteTarget.id)}&group_id=eq.${q(groupId)}`,{method:'DELETE'});await loadHistory()}else{state.history=state.history.filter(x=>x.id!==deleteTarget.id);state.weightHistory=state.history.slice(0,50);saveLocal();renderHistory()}close('deleteOverlay');deleteTarget=null;toast('已删除；不再参与智能随机')}catch(e){toast('删除失败：'+e.message,2600)}}
async function clearHistory(){try{if(cloud){await rest(`dinner_history?group_id=eq.${q(groupId)}`,{method:'DELETE'});await loadHistory()}else{state.history=[];state.weightHistory=[];saveLocal();renderHistory()}close('clearOverlay');toast('最近历史已清空')}catch(e){toast('清空失败：'+e.message,2600)}}
function resetHold(){clearActive=false;cancelAnimationFrame(holdRaf);$('holdProgress').style.width='0%';$('holdLabel').textContent='按住 1.2 秒确认清空'}function holdStep(t){if(!clearActive)return;const r=Math.min(1,(t-holdStart)/1200);$('holdProgress').style.width=r*100+'%';$('holdLabel').textContent=r>=1?'正在清空…':`继续按住 ${Math.max(0,1.2-(t-holdStart)/1000).toFixed(1)} 秒`;if(r>=1){clearActive=false;return clearHistory()}holdRaf=requestAnimationFrame(holdStep)}$('holdClearBtn').onpointerdown=e=>{e.preventDefault();clearActive=true;holdStart=performance.now();holdRaf=requestAnimationFrame(holdStep)};['pointerup','pointercancel'].forEach(ev=>$('holdClearBtn').addEventListener(ev,()=>{if(clearActive){resetHold();toast('已取消清空',700)}}));
async function setMode(m){state.mode=m;renderMode();if(cloud){try{await rest('dinner_group_state?on_conflict=group_id',{method:'POST',body:{group_id:groupId,random_mode:m,filters:{},updated_by:session.user.id},prefer:'resolution=merge-duplicates,return=minimal'})}catch(e){toast('同步失败：'+e.message,2200)}}else saveLocal()}
async function setEnabled(x,v){if(cloud){try{await rest(`dinner_candidates?id=eq.${q(x.id)}&group_id=eq.${q(groupId)}`,{method:'PATCH',body:{enabled:v},prefer:'return=minimal'});await loadCandidates()}catch(e){toast('同步失败：'+e.message,2200);renderManager()}}else{x.enabled=v;saveLocal();renderCandidates();renderManager()}}
async function delCandidate(x){if(cloud){try{await rest(`dinner_candidates?id=eq.${q(x.id)}&group_id=eq.${q(groupId)}`,{method:'DELETE'});await loadCandidates()}catch(e){toast('删除失败：'+e.message,2200)}}else{state.candidates=state.candidates.filter(y=>y.id!==x.id);saveLocal();renderCandidates();renderManager()}}
async function addCandidate(){const name=$('newCandidateInput').value.trim();if(!name)return toast('请输入候选名称');if(state.candidates.some(x=>x.name===name))return toast('这个候选已经存在');try{if(cloud){await rest('dinner_candidates',{method:'POST',body:{group_id:groupId,name,emoji:'🍽️',enabled:true,created_by:session.user.id},prefer:'return=minimal'});await loadCandidates()}else{state.candidates.push({id:uid(),name,emoji:'🍽️',enabled:true});saveLocal();renderCandidates();renderManager()}$('newCandidateInput').value='';toast(`已添加「${name}」`)}catch(e){toast('添加失败：'+e.message,2200)}}
async function loadCandidates(){const data=await rest(`dinner_candidates?select=id,name,emoji,enabled&group_id=eq.${q(groupId)}&order=created_at.asc`);state.candidates=data||[];renderCandidates();renderManager()}
async function loadHistory(){const fields='id,candidate_id,candidate_name_snapshot,emoji_snapshot,meal_date,meal_period,note,created_by,created_at';const [a,b]=await Promise.all([rest(`dinner_history?select=${fields}&group_id=eq.${q(groupId)}&order=meal_date.desc,created_at.desc&limit=${historyLimit}`),rest(`dinner_history?select=candidate_id,meal_date&group_id=eq.${q(groupId)}&order=meal_date.desc,created_at.desc&limit=50`)]);state.history=a||[];state.weightHistory=b||[];renderHistory()}
async function loadGroupState(){const data=await rest(`dinner_group_state?select=random_mode&group_id=eq.${q(groupId)}&limit=1`);state.mode=data?.[0]?.random_mode==='smart'?'smart':'fair';renderMode()}
async function syncTick(){if(!cloud||syncBusy||document.hidden)return;syncBusy=true;try{await Promise.all([loadCandidates(),loadHistory(),loadGroupState()])}catch(e){console.warn('sync failed',e)}finally{syncBusy=false}}
function startSync(){stopSync();syncTimer=setInterval(syncTick,3000);document.addEventListener('visibilitychange',onVisible)}function stopSync(){if(syncTimer){clearInterval(syncTimer);syncTimer=0}document.removeEventListener('visibilitychange',onVisible)}function onVisible(){if(!document.hidden)syncTick()}
async function activate(sess){session=sess;const uidv=sess?.user?.id;if(!uidv)throw new Error('无法读取登录用户');const data=await rest(`dinner_group_members?select=group_id,display_name&user_id=eq.${q(uidv)}&limit=1`);if(!data?.length){cloud=false;renderSync();toast('此账号不在共享菜单成员中');return false}groupId=data[0].group_id;myName=data[0].display_name;const [g,m]=await Promise.all([rest(`dinner_groups?select=name&id=eq.${q(groupId)}&limit=1`),rest(`dinner_group_members?select=user_id,display_name,role&group_id=eq.${q(groupId)}`)]);if(!g?.length)throw new Error('共享组不存在');groupName=g[0].name;members=m||[];cloud=true;historyLimit=20;await Promise.all([loadCandidates(),loadHistory(),loadGroupState()]);startSync();renderSync();return true}
async function login(){const email=$('loginEmail').value.trim(),password=$('loginPassword').value;if(!email||!password)return toast('请输入邮箱和密码');$('loginBtn').disabled=true;try{const data=await authRequest('/auth/v1/token?grant_type=password',{body:{email,password}});session=data;saveAuth();if(await activate(data)){close('accountOverlay');$('loginPassword').value='';toast('多人同步已开启')}}catch(e){session=null;saveAuth();toast(e.message.includes('fetch')?'无法连接同步服务，请检查当前网络':'登录失败：邮箱或密码错误',2600)}finally{$('loginBtn').disabled=false}}
async function logout(){stopSync();try{if(session?.access_token)await fetch(URL+'/auth/v1/logout',{method:'POST',headers:authHeaders()})}catch{}session=null;saveAuth();cloud=false;groupId=null;groupName='';myName='';members=[];loadLocal();renderAll();renderSync();close('accountOverlay');toast('已回到单机模式')}
function account(){if(cloud){$('loginFormWrap').classList.add('hidden');$('loggedWrap').classList.remove('hidden');$('accountTitle').textContent='共享账户';$('loggedText').textContent=`${myName} · ${groupName} · 候选、筛选、随机模式与历史会自动同步。`}else{$('loginFormWrap').classList.remove('hidden');$('loggedWrap').classList.add('hidden');$('accountTitle').textContent='登录共享菜单'}open('accountOverlay')}
function renderAll(){renderMode();renderCandidates();renderHistory();renderJaw();$('soundBtn').textContent=state.sound?'🔊':'🔇'}
$('fairBtn').onclick=()=>setMode('fair');$('smartBtn').onclick=()=>setMode('smart');$('manageBtn').onclick=()=>{renderManager();open('managerOverlay')};$('drawThreeBtn').onclick=()=>draw3(false);$('replaceThreeBtn').onclick=()=>draw3(true);$('startFinalBtn').onclick=()=>final(false);$('regretBtn').onclick=regret;$('confirmBtn').onclick=()=>openRecord(state.result?.id||'');$('addHistoryBtn').onclick=()=>openRecord();$('saveRecordBtn').onclick=saveRecord;$('confirmDeleteBtn').onclick=deleteHistory;$('clearHistoryBtn').onclick=()=>{resetHold();open('clearOverlay')};$('loadMoreBtn').onclick=async()=>{historyLimit+=20;if(cloud)await loadHistory()};$('addCandidateBtn').onclick=addCandidate;$('recordNote').oninput=()=>{$('noteCount').textContent=`${$('recordNote').value.length}/500`};$('accountBtn').onclick=account;$('syncActionBtn').onclick=account;$('loginBtn').onclick=login;$('logoutBtn').onclick=logout;$('soundBtn').onclick=()=>{state.sound=!state.sound;saveLocal();$('soundBtn').textContent=state.sound?'🔊':'🔇'};
loadLocal();renderAll();renderSync();
(async()=>{session=readAuth();if(!session)return;try{if(await ensureAuth())await activate(session);else{session=null;saveAuth()}}catch(e){console.warn('restore session failed',e);session=null;saveAuth();cloud=false;renderSync()}})();