(function(global){
  'use strict';
  const colors=[
    {code:"A1",hex:"#F9F0CD",series:"A",standard:true,special:null},
    {code:"A2",hex:"#FBFBD4",series:"A",standard:true,special:null},
    {code:"A3",hex:"#FAFC9F",series:"A",standard:true,special:null},
    {code:"A4",hex:"#FFE953",series:"A",standard:true,special:null},
    {code:"A5",hex:"#F4D738",series:"A",standard:true,special:null},
    {code:"A6",hex:"#FDAD49",series:"A",standard:true,special:null},
    {code:"A7",hex:"#FF7C2F",series:"A",standard:true,special:null},
    {code:"A8",hex:"#EACA49",series:"A",standard:true,special:null},
    {code:"A9",hex:"#FF995A",series:"A",standard:true,special:null},
    {code:"A10",hex:"#FF9D55",series:"A",standard:true,special:null},
    {code:"A11",hex:"#FFDD99",series:"A",standard:true,special:null},
    {code:"A12",hex:"#FCB58F",series:"A",standard:true,special:null},
    {code:"A13",hex:"#FFBB59",series:"A",standard:true,special:null},
    {code:"A14",hex:"#FF6D40",series:"A",standard:true,special:null},
    {code:"A15",hex:"#FDFF44",series:"A",standard:true,special:null},
    {code:"A16",hex:"#FEF9AE",series:"A",standard:true,special:null},
    {code:"A17",hex:"#FFE36E",series:"A",standard:true,special:null},
    {code:"A18",hex:"#FECF98",series:"A",standard:true,special:null},
    {code:"A19",hex:"#FD7B72",series:"A",standard:true,special:null},
    {code:"A20",hex:"#EFCD67",series:"A",standard:true,special:null},
    {code:"A21",hex:"#FFE395",series:"A",standard:true,special:null},
    {code:"A22",hex:"#FFF3A4",series:"A",standard:true,special:null},
    {code:"A23",hex:"#F3D5BF",series:"A",standard:true,special:null},
    {code:"A24",hex:"#FBF8C9",series:"A",standard:true,special:null},
    {code:"A25",hex:"#FFD67D",series:"A",standard:true,special:null},
    {code:"A26",hex:"#FFBB27",series:"A",standard:true,special:null},
    {code:"B1",hex:"#E6EE32",series:"B",standard:true,special:null},
    {code:"B2",hex:"#5BE419",series:"B",standard:true,special:null},
    {code:"B3",hex:"#7CEE9D",series:"B",standard:true,special:null},
    {code:"B4",hex:"#1EF942",series:"B",standard:true,special:null},
    {code:"B5",hex:"#00BD35",series:"B",standard:true,special:null},
    {code:"B6",hex:"#5AE8BA",series:"B",standard:true,special:null},
    {code:"B7",hex:"#03AC88",series:"B",standard:true,special:null},
    {code:"B8",hex:"#029D26",series:"B",standard:true,special:null},
    {code:"B9",hex:"#26523A",series:"B",standard:true,special:null},
    {code:"B10",hex:"#95D3C2",series:"B",standard:true,special:null},
    {code:"B11",hex:"#5D722A",series:"B",standard:true,special:null},
    {code:"B12",hex:"#156F40",series:"B",standard:true,special:null},
    {code:"B13",hex:"#D9F794",series:"B",standard:true,special:null},
    {code:"B14",hex:"#ADE945",series:"B",standard:true,special:null},
    {code:"B15",hex:"#2E5132",series:"B",standard:true,special:null},
    {code:"B16",hex:"#C6ED9C",series:"B",standard:true,special:null},
    {code:"B17",hex:"#9BB13A",series:"B",standard:true,special:null},
    {code:"B18",hex:"#E6EE49",series:"B",standard:true,special:null},
    {code:"B19",hex:"#25B88C",series:"B",standard:true,special:null},
    {code:"B20",hex:"#C2F0CC",series:"B",standard:true,special:null},
    {code:"B21",hex:"#146A6B",series:"B",standard:true,special:null},
    {code:"B22",hex:"#0B3C43",series:"B",standard:true,special:null},
    {code:"B23",hex:"#303921",series:"B",standard:true,special:null},
    {code:"B24",hex:"#EEFCA5",series:"B",standard:true,special:null},
    {code:"B25",hex:"#4E846D",series:"B",standard:true,special:null},
    {code:"B26",hex:"#8C7A36",series:"B",standard:true,special:null},
    {code:"B27",hex:"#D1DCC1",series:"B",standard:true,special:null},
    {code:"B28",hex:"#9EE5B9",series:"B",standard:true,special:null},
    {code:"B29",hex:"#C5E254",series:"B",standard:true,special:null},
    {code:"B30",hex:"#ECFBD0",series:"B",standard:true,special:null},
    {code:"B31",hex:"#C4E6B5",series:"B",standard:true,special:null},
    {code:"B32",hex:"#9BAB5A",series:"B",standard:true,special:null},
    {code:"C1",hex:"#E8FFE7",series:"C",standard:true,special:null},
    {code:"C2",hex:"#BCF9F6",series:"C",standard:true,special:null},
    {code:"C3",hex:"#A0E2FB",series:"C",standard:true,special:null},
    {code:"C4",hex:"#42CCFF",series:"C",standard:true,special:null},
    {code:"C5",hex:"#01ACEB",series:"C",standard:true,special:null},
    {code:"C6",hex:"#50A9F0",series:"C",standard:true,special:null},
    {code:"C7",hex:"#0188D3",series:"C",standard:true,special:null},
    {code:"C8",hex:"#1054C0",series:"C",standard:true,special:null},
    {code:"C9",hex:"#314BCA",series:"C",standard:true,special:null},
    {code:"C10",hex:"#3EBCE2",series:"C",standard:true,special:null},
    {code:"C11",hex:"#03B9B9",series:"C",standard:true,special:null},
    {code:"C12",hex:"#1C334D",series:"C",standard:true,special:null},
    {code:"C13",hex:"#CDE8FF",series:"C",standard:true,special:null},
    {code:"C14",hex:"#D5FDFF",series:"C",standard:true,special:null},
    {code:"C15",hex:"#23C4C6",series:"C",standard:true,special:null},
    {code:"C16",hex:"#1757A8",series:"C",standard:true,special:null},
    {code:"C17",hex:"#50D3EC",series:"C",standard:true,special:null},
    {code:"C18",hex:"#1C3344",series:"C",standard:true,special:null},
    {code:"C19",hex:"#1787A2",series:"C",standard:true,special:null},
    {code:"C20",hex:"#0082BE",series:"C",standard:true,special:null},
    {code:"C21",hex:"#BEDDFF",series:"C",standard:true,special:null},
    {code:"C22",hex:"#67B4BE",series:"C",standard:true,special:null},
    {code:"C23",hex:"#C2DCEB",series:"C",standard:true,special:null},
    {code:"C24",hex:"#7DC4FF",series:"C",standard:true,special:null},
    {code:"C25",hex:"#A9E5E5",series:"C",standard:true,special:null},
    {code:"C26",hex:"#2F99B3",series:"C",standard:true,special:null},
    {code:"C27",hex:"#EBF5FC",series:"C",standard:true,special:null},
    {code:"C28",hex:"#BBCFED",series:"C",standard:true,special:null},
    {code:"C29",hex:"#4B5BA3",series:"C",standard:true,special:null},
    {code:"D1",hex:"#AEB4F2",series:"D",standard:true,special:null},
    {code:"D2",hex:"#858EDD",series:"D",standard:true,special:null},
    {code:"D3",hex:"#3054AF",series:"D",standard:true,special:null},
    {code:"D4",hex:"#182A84",series:"D",standard:true,special:null},
    {code:"D5",hex:"#B843C5",series:"D",standard:true,special:null},
    {code:"D6",hex:"#AC7BDE",series:"D",standard:true,special:null},
    {code:"D7",hex:"#6E399A",series:"D",standard:true,special:null},
    {code:"D8",hex:"#E2D3FF",series:"D",standard:true,special:null},
    {code:"D9",hex:"#D5B9F8",series:"D",standard:true,special:null},
    {code:"D10",hex:"#361B50",series:"D",standard:true,special:null},
    {code:"D11",hex:"#B9BAE1",series:"D",standard:true,special:null},
    {code:"D12",hex:"#DE9AD4",series:"D",standard:true,special:null},
    {code:"D13",hex:"#B90295",series:"D",standard:true,special:null},
    {code:"D14",hex:"#8B279B",series:"D",standard:true,special:null},
    {code:"D15",hex:"#2F1F90",series:"D",standard:true,special:null},
    {code:"D16",hex:"#E2E1EE",series:"D",standard:true,special:null},
    {code:"D17",hex:"#C4D4F6",series:"D",standard:true,special:null},
    {code:"D18",hex:"#A45EC7",series:"D",standard:true,special:null},
    {code:"D19",hex:"#D8C3D7",series:"D",standard:true,special:null},
    {code:"D20",hex:"#9C32B2",series:"D",standard:true,special:null},
    {code:"D21",hex:"#9A009B",series:"D",standard:true,special:null},
    {code:"D22",hex:"#333995",series:"D",standard:true,special:null},
    {code:"D23",hex:"#EADAFC",series:"D",standard:true,special:null},
    {code:"D24",hex:"#7786E5",series:"D",standard:true,special:null},
    {code:"D25",hex:"#484FC7",series:"D",standard:true,special:null},
    {code:"D26",hex:"#E9C3F6",series:"D",standard:true,special:null},
    {code:"E1",hex:"#FDD3CC",series:"E",standard:true,special:null},
    {code:"E2",hex:"#FECDDF",series:"E",standard:true,special:null},
    {code:"E3",hex:"#FF97C3",series:"E",standard:true,special:null},
    {code:"E4",hex:"#E8649E",series:"E",standard:true,special:null},
    {code:"E5",hex:"#F551A2",series:"E",standard:true,special:null},
    {code:"E6",hex:"#FF346B",series:"E",standard:true,special:null},
    {code:"E7",hex:"#C63578",series:"E",standard:true,special:null},
    {code:"E8",hex:"#FFDBE9",series:"E",standard:true,special:null},
    {code:"E9",hex:"#E970CC",series:"E",standard:true,special:null},
    {code:"E10",hex:"#D33893",series:"E",standard:true,special:null},
    {code:"E11",hex:"#FCDDD2",series:"E",standard:true,special:null},
    {code:"E12",hex:"#FFA1C5",series:"E",standard:true,special:null},
    {code:"E13",hex:"#B6006D",series:"E",standard:true,special:null},
    {code:"E14",hex:"#FFD1BA",series:"E",standard:true,special:null},
    {code:"E15",hex:"#F2CFD0",series:"E",standard:true,special:null},
    {code:"E16",hex:"#FFECDE",series:"E",standard:true,special:null},
    {code:"E17",hex:"#FFE2EA",series:"E",standard:true,special:null},
    {code:"E18",hex:"#FFC9D6",series:"E",standard:true,special:null},
    {code:"E19",hex:"#FFD2E7",series:"E",standard:true,special:null},
    {code:"E20",hex:"#D8C7D1",series:"E",standard:true,special:null},
    {code:"E21",hex:"#BD9DA1",series:"E",standard:true,special:null},
    {code:"E22",hex:"#CC78A7",series:"E",standard:true,special:null},
    {code:"E23",hex:"#937A8D",series:"E",standard:true,special:null},
    {code:"E24",hex:"#F6E4F9",series:"E",standard:true,special:null},
    {code:"F1",hex:"#FD957B",series:"F",standard:true,special:null},
    {code:"F2",hex:"#FC3D45",series:"F",standard:true,special:null},
    {code:"F3",hex:"#F74941",series:"F",standard:true,special:null},
    {code:"F4",hex:"#FC283C",series:"F",standard:true,special:null},
    {code:"F5",hex:"#D80127",series:"F",standard:true,special:null},
    {code:"F6",hex:"#B0443D",series:"F",standard:true,special:null},
    {code:"F7",hex:"#971937",series:"F",standard:true,special:null},
    {code:"F8",hex:"#BC0127",series:"F",standard:true,special:null},
    {code:"F9",hex:"#E2677A",series:"F",standard:true,special:null},
    {code:"F10",hex:"#A74D22",series:"F",standard:true,special:null},
    {code:"F11",hex:"#6F201F",series:"F",standard:true,special:null},
    {code:"F12",hex:"#FD4D6A",series:"F",standard:true,special:null},
    {code:"F13",hex:"#DD422F",series:"F",standard:true,special:null},
    {code:"F14",hex:"#FFA9AD",series:"F",standard:true,special:null},
    {code:"F15",hex:"#C80020",series:"F",standard:true,special:null},
    {code:"F16",hex:"#FFD9C8",series:"F",standard:true,special:null},
    {code:"F17",hex:"#F79B71",series:"F",standard:true,special:null},
    {code:"F18",hex:"#D37C46",series:"F",standard:true,special:null},
    {code:"F19",hex:"#C1444A",series:"F",standard:true,special:null},
    {code:"F20",hex:"#CD9391",series:"F",standard:true,special:null},
    {code:"F21",hex:"#F4B1B4",series:"F",standard:true,special:null},
    {code:"F22",hex:"#FFD0CB",series:"F",standard:true,special:null},
    {code:"F23",hex:"#F57E66",series:"F",standard:true,special:null},
    {code:"F24",hex:"#FCC1C4",series:"F",standard:true,special:null},
    {code:"F25",hex:"#E54B4F",series:"F",standard:true,special:null},
    {code:"G1",hex:"#FFE2CE",series:"G",standard:true,special:null},
    {code:"G2",hex:"#FFCAAA",series:"G",standard:true,special:null},
    {code:"G3",hex:"#F4C3A5",series:"G",standard:true,special:null},
    {code:"G4",hex:"#E1B383",series:"G",standard:true,special:null},
    {code:"G5",hex:"#ED9435",series:"G",standard:true,special:null},
    {code:"G6",hex:"#F59734",series:"G",standard:true,special:null},
    {code:"G7",hex:"#9D5B3E",series:"G",standard:true,special:null},
    {code:"G8",hex:"#592A21",series:"G",standard:true,special:null},
    {code:"G9",hex:"#E6B483",series:"G",standard:true,special:null},
    {code:"G10",hex:"#C88135",series:"G",standard:true,special:null},
    {code:"G11",hex:"#E0C593",series:"G",standard:true,special:null},
    {code:"G12",hex:"#EBBB83",series:"G",standard:true,special:null},
    {code:"G13",hex:"#B7714A",series:"G",standard:true,special:null},
    {code:"G14",hex:"#8D614C",series:"G",standard:true,special:null},
    {code:"G15",hex:"#FCF9E0",series:"G",standard:true,special:null},
    {code:"G16",hex:"#F2D9BA",series:"G",standard:true,special:null},
    {code:"G17",hex:"#56403C",series:"G",standard:true,special:null},
    {code:"G18",hex:"#FFE4CC",series:"G",standard:true,special:null},
    {code:"G19",hex:"#E1943A",series:"G",standard:true,special:null},
    {code:"G20",hex:"#A94023",series:"G",standard:true,special:null},
    {code:"G21",hex:"#CB8E77",series:"G",standard:true,special:null},
    {code:"H1",hex:"#E2E2E2",series:"H",standard:true,special:null},
    {code:"H2",hex:"#FFFFFF",series:"H",standard:true,special:null},
    {code:"H3",hex:"#B3B3B3",series:"H",standard:true,special:null},
    {code:"H4",hex:"#868686",series:"H",standard:true,special:null},
    {code:"H5",hex:"#474747",series:"H",standard:true,special:null},
    {code:"H6",hex:"#2C2C2C",series:"H",standard:true,special:null},
    {code:"H7",hex:"#000000",series:"H",standard:true,special:null},
    {code:"H8",hex:"#E7D6DB",series:"H",standard:true,special:null},
    {code:"H9",hex:"#E4E7E3",series:"H",standard:true,special:null},
    {code:"H10",hex:"#EEE9EA",series:"H",standard:true,special:null},
    {code:"H11",hex:"#CECDD5",series:"H",standard:true,special:null},
    {code:"H12",hex:"#FFF5ED",series:"H",standard:true,special:null},
    {code:"H13",hex:"#F3E1C9",series:"H",standard:true,special:null},
    {code:"H14",hex:"#CFD7D3",series:"H",standard:true,special:null},
    {code:"H15",hex:"#98A6A8",series:"H",standard:true,special:null},
    {code:"H16",hex:"#3B2F23",series:"H",standard:true,special:null},
    {code:"H17",hex:"#F1EDED",series:"H",standard:true,special:null},
    {code:"H18",hex:"#FFFDF0",series:"H",standard:true,special:null},
    {code:"H19",hex:"#F6EFE2",series:"H",standard:true,special:null},
    {code:"H20",hex:"#949FA3",series:"H",standard:true,special:null},
    {code:"H21",hex:"#F7F3E4",series:"H",standard:true,special:null},
    {code:"H22",hex:"#CACAD5",series:"H",standard:true,special:null},
    {code:"H23",hex:"#9A9D94",series:"H",standard:true,special:null},
    {code:"M1",hex:"#BCC6B8",series:"M",standard:true,special:null},
    {code:"M2",hex:"#8AA385",series:"M",standard:true,special:null},
    {code:"M3",hex:"#697D80",series:"M",standard:true,special:null},
    {code:"M4",hex:"#DACEBE",series:"M",standard:true,special:null},
    {code:"M5",hex:"#D0CCAA",series:"M",standard:true,special:null},
    {code:"M6",hex:"#B0A782",series:"M",standard:true,special:null},
    {code:"M7",hex:"#B4A497",series:"M",standard:true,special:null},
    {code:"M8",hex:"#B38281",series:"M",standard:true,special:null},
    {code:"M9",hex:"#A58767",series:"M",standard:true,special:null},
    {code:"M10",hex:"#C5B1BC",series:"M",standard:true,special:null},
    {code:"M11",hex:"#9F7494",series:"M",standard:true,special:null},
    {code:"M12",hex:"#644749",series:"M",standard:true,special:null},
    {code:"M13",hex:"#D19066",series:"M",standard:true,special:null},
    {code:"M14",hex:"#C77361",series:"M",standard:true,special:null},
    {code:"M15",hex:"#757D7B",series:"M",standard:true,special:null},
    {code:"P1",hex:"#FCF8F9",series:"P",standard:false,special:{"name":"珠光","note":"珠光系列；屏幕 HEX 只能近似表现光泽。"}},
    {code:"P2",hex:"#BDA9AB",series:"P",standard:false,special:{"name":"珠光","note":"珠光系列；屏幕 HEX 只能近似表现光泽。"}},
    {code:"P3",hex:"#AEDDA9",series:"P",standard:false,special:{"name":"珠光","note":"珠光系列；屏幕 HEX 只能近似表现光泽。"}},
    {code:"P4",hex:"#FDA49E",series:"P",standard:false,special:{"name":"珠光","note":"珠光系列；屏幕 HEX 只能近似表现光泽。"}},
    {code:"P5",hex:"#EC8D3D",series:"P",standard:false,special:{"name":"珠光","note":"珠光系列；屏幕 HEX 只能近似表现光泽。"}},
    {code:"P6",hex:"#60CFA8",series:"P",standard:false,special:{"name":"珠光","note":"珠光系列；屏幕 HEX 只能近似表现光泽。"}},
    {code:"P7",hex:"#EB9271",series:"P",standard:false,special:{"name":"珠光","note":"珠光系列；屏幕 HEX 只能近似表现光泽。"}},
    {code:"P8",hex:"#F0D958",series:"P",standard:false,special:{"name":"珠光","note":"珠光系列；屏幕 HEX 只能近似表现光泽。"}},
    {code:"P9",hex:"#D9D9D9",series:"P",standard:false,special:{"name":"珠光","note":"珠光系列；屏幕 HEX 只能近似表现光泽。"}},
    {code:"P10",hex:"#D5C8E9",series:"P",standard:false,special:{"name":"珠光","note":"珠光系列；屏幕 HEX 只能近似表现光泽。"}},
    {code:"P11",hex:"#F3ECC8",series:"P",standard:false,special:{"name":"珠光","note":"珠光系列；屏幕 HEX 只能近似表现光泽。"}},
    {code:"P12",hex:"#E6EEF1",series:"P",standard:false,special:{"name":"珠光","note":"珠光系列；屏幕 HEX 只能近似表现光泽。"}},
    {code:"P13",hex:"#A9CBF1",series:"P",standard:false,special:{"name":"珠光","note":"珠光系列；屏幕 HEX 只能近似表现光泽。"}},
    {code:"P14",hex:"#3177B0",series:"P",standard:false,special:{"name":"珠光","note":"珠光系列；屏幕 HEX 只能近似表现光泽。"}},
    {code:"P15",hex:"#668575",series:"P",standard:false,special:{"name":"珠光","note":"珠光系列；屏幕 HEX 只能近似表现光泽。"}},
    {code:"P16",hex:"#FFBE46",series:"P",standard:false,special:{"name":"珠光","note":"珠光系列；屏幕 HEX 只能近似表现光泽。"}},
    {code:"P17",hex:"#FFA324",series:"P",standard:false,special:{"name":"珠光","note":"珠光系列；屏幕 HEX 只能近似表现光泽。"}},
    {code:"P18",hex:"#FEB89F",series:"P",standard:false,special:{"name":"珠光","note":"珠光系列；屏幕 HEX 只能近似表现光泽。"}},
    {code:"P19",hex:"#FFE0E8",series:"P",standard:false,special:{"name":"珠光","note":"珠光系列；屏幕 HEX 只能近似表现光泽。"}},
    {code:"P20",hex:"#FEBECF",series:"P",standard:false,special:{"name":"珠光","note":"珠光系列；屏幕 HEX 只能近似表现光泽。"}},
    {code:"P21",hex:"#ECBEC0",series:"P",standard:false,special:{"name":"珠光","note":"珠光系列；屏幕 HEX 只能近似表现光泽。"}},
    {code:"P22",hex:"#E4A89E",series:"P",standard:false,special:{"name":"珠光","note":"珠光系列；屏幕 HEX 只能近似表现光泽。"}},
    {code:"P23",hex:"#A56269",series:"P",standard:false,special:{"name":"珠光","note":"珠光系列；屏幕 HEX 只能近似表现光泽。"}},
    {code:"Q1",hex:"#F2A5E8",series:"Q",standard:false,special:{"name":"温变","note":"温变系列；实际颜色会随温度变化。"}},
    {code:"Q2",hex:"#73B29E",series:"Q",standard:false,special:{"name":"温变","note":"温变系列；实际颜色会随温度变化。"}},
    {code:"Q3",hex:"#FFFF00",series:"Q",standard:false,special:{"name":"温变","note":"温变系列；实际颜色会随温度变化。"}},
    {code:"Q4",hex:"#FFEBFA",series:"Q",standard:false,special:{"name":"温变","note":"温变系列；实际颜色会随温度变化。"}},
    {code:"Q5",hex:"#4F5E5B",series:"Q",standard:false,special:{"name":"温变","note":"温变系列；实际颜色会随温度变化。"}},
    {code:"R1",hex:"#D50E21",series:"R",standard:false,special:{"name":"果冻","note":"果冻系列；半透明质感。"}},
    {code:"R2",hex:"#F92E83",series:"R",standard:false,special:{"name":"果冻","note":"果冻系列；半透明质感。"}},
    {code:"R3",hex:"#FD8225",series:"R",standard:false,special:{"name":"果冻","note":"果冻系列；半透明质感。"}},
    {code:"R4",hex:"#F8EC31",series:"R",standard:false,special:{"name":"果冻","note":"果冻系列；半透明质感。"}},
    {code:"R5",hex:"#34C75B",series:"R",standard:false,special:{"name":"果冻","note":"果冻系列；半透明质感。"}},
    {code:"R6",hex:"#25B891",series:"R",standard:false,special:{"name":"果冻","note":"果冻系列；半透明质感。"}},
    {code:"R7",hex:"#17779D",series:"R",standard:false,special:{"name":"果冻","note":"果冻系列；半透明质感。"}},
    {code:"R8",hex:"#1B60C3",series:"R",standard:false,special:{"name":"果冻","note":"果冻系列；半透明质感。"}},
    {code:"R9",hex:"#9A56B4",series:"R",standard:false,special:{"name":"果冻","note":"果冻系列；半透明质感。"}},
    {code:"R10",hex:"#FFDB4D",series:"R",standard:false,special:{"name":"果冻","note":"果冻系列；半透明质感。"}},
    {code:"R11",hex:"#FFEBFA",series:"R",standard:false,special:{"name":"果冻","note":"果冻系列；半透明质感。"}},
    {code:"R12",hex:"#D8D5CE",series:"R",standard:false,special:{"name":"果冻","note":"果冻系列；半透明质感。"}},
    {code:"R13",hex:"#55514C",series:"R",standard:false,special:{"name":"果冻","note":"果冻系列；半透明质感。"}},
    {code:"R14",hex:"#9EE4DF",series:"R",standard:false,special:{"name":"果冻","note":"果冻系列；半透明质感。"}},
    {code:"R15",hex:"#77CEE9",series:"R",standard:false,special:{"name":"果冻","note":"果冻系列；半透明质感。"}},
    {code:"R16",hex:"#3DCFCA",series:"R",standard:false,special:{"name":"果冻","note":"果冻系列；半透明质感。"}},
    {code:"R17",hex:"#4A867A",series:"R",standard:false,special:{"name":"果冻","note":"果冻系列；半透明质感。"}},
    {code:"R18",hex:"#7FCD9D",series:"R",standard:false,special:{"name":"果冻","note":"果冻系列；半透明质感。"}},
    {code:"R19",hex:"#CDE55D",series:"R",standard:false,special:{"name":"果冻","note":"果冻系列；半透明质感。"}},
    {code:"R20",hex:"#E8C7B4",series:"R",standard:false,special:{"name":"果冻","note":"果冻系列；半透明质感。"}},
    {code:"R21",hex:"#AD6F3C",series:"R",standard:false,special:{"name":"果冻","note":"果冻系列；半透明质感。"}},
    {code:"R22",hex:"#6C372F",series:"R",standard:false,special:{"name":"果冻","note":"果冻系列；半透明质感。"}},
    {code:"R23",hex:"#FEB872",series:"R",standard:false,special:{"name":"果冻","note":"果冻系列；半透明质感。"}},
    {code:"R24",hex:"#F2C1C0",series:"R",standard:false,special:{"name":"果冻","note":"果冻系列；半透明质感。"}},
    {code:"R25",hex:"#C9675D",series:"R",standard:false,special:{"name":"果冻","note":"果冻系列；半透明质感。"}},
    {code:"R26",hex:"#D293BE",series:"R",standard:false,special:{"name":"果冻","note":"果冻系列；半透明质感。"}},
    {code:"R27",hex:"#EA8CB1",series:"R",standard:false,special:{"name":"果冻","note":"果冻系列；半透明质感。"}},
    {code:"R28",hex:"#9C87D6",series:"R",standard:false,special:{"name":"果冻","note":"果冻系列；半透明质感。"}},
    {code:"T1",hex:"#E2DFD7",series:"T",standard:false,special:{"name":"透明","note":"透明系列；T1 为半透明白色。"}},
    {code:"Y1",hex:"#FD6FB4",series:"Y",standard:false,special:{"name":"夜光","note":"夜光系列；暗处发光效果不能由单一 HEX 表示。"}},
    {code:"Y2",hex:"#FEB481",series:"Y",standard:false,special:{"name":"夜光","note":"夜光系列；暗处发光效果不能由单一 HEX 表示。"}},
    {code:"Y3",hex:"#D7FAA0",series:"Y",standard:false,special:{"name":"夜光","note":"夜光系列；暗处发光效果不能由单一 HEX 表示。"}},
    {code:"Y4",hex:"#8BDBFA",series:"Y",standard:false,special:{"name":"夜光","note":"夜光系列；暗处发光效果不能由单一 HEX 表示。"}},
    {code:"Y5",hex:"#E987EA",series:"Y",standard:false,special:{"name":"夜光","note":"夜光系列；暗处发光效果不能由单一 HEX 表示。"}},
    {code:"ZG1",hex:"#F28985",series:"ZG",standard:false,special:{"name":"光变","note":"光变系列；未照射时透明，表中 HEX 为紫外线照射后的显色参考。"}},
    {code:"ZG2",hex:"#ECA55D",series:"ZG",standard:false,special:{"name":"光变","note":"光变系列；未照射时透明，表中 HEX 为紫外线照射后的显色参考。"}},
    {code:"ZG3",hex:"#E8CE6A",series:"ZG",standard:false,special:{"name":"光变","note":"光变系列；未照射时透明，表中 HEX 为紫外线照射后的显色参考。"}},
    {code:"ZG4",hex:"#88C772",series:"ZG",standard:false,special:{"name":"光变","note":"光变系列；未照射时透明，表中 HEX 为紫外线照射后的显色参考。"}},
    {code:"ZG5",hex:"#718CBF",series:"ZG",standard:false,special:{"name":"光变","note":"光变系列；未照射时透明，表中 HEX 为紫外线照射后的显色参考。"}},
    {code:"ZG6",hex:"#77ACD2",series:"ZG",standard:false,special:{"name":"光变","note":"光变系列；未照射时透明，表中 HEX 为紫外线照射后的显色参考。"}},
    {code:"ZG7",hex:"#E88F8C",series:"ZG",standard:false,special:{"name":"光变","note":"光变系列；未照射时透明，表中 HEX 为紫外线照射后的显色参考。"}},
    {code:"ZG8",hex:"#AE84BD",series:"ZG",standard:false,special:{"name":"光变","note":"光变系列；未照射时透明，表中 HEX 为紫外线照射后的显色参考。"}}
  ];
  global.MARDPalette={
    sourceUrl:'https://www.pixel-beads.com/zh/mard-bead-color-chart',
    sourceTitle:'MARD 拼豆色号大全 (2026重新修订版)',
    revision:'2026',
    colors,
    seriesOrder:["A","B","C","D","E","F","G","H","M","P","Q","R","T","Y","ZG"],
    standardCount:colors.filter(x=>x.standard).length,
    totalCount:colors.length,
    notes:{
      standard:'标准 221 色：A–H 与 M。',
      full:'完整 291 色：标准 221 色 + P/Q/R/T/Y/ZG 扩展系列。',
      display:'HEX 为屏幕显示近似值；实物颜色会受光线、批次与材质状态影响。',
      special:'特殊系列的珠光、温变、半透明、夜光与光变效果不能由单一 HEX 完整表示。'
    }
  };
})(window);
