
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);
alter table public.admin_users enable row level security;
revoke all on table public.admin_users from anon, authenticated;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.admin_users
    where user_id = auth.uid()
  );
$$;
revoke all on function public.is_admin() from public;
revoke all on function public.is_admin() from anon;
grant execute on function public.is_admin() to authenticated;

-- OMITTED PRIVATE SEED: admin assignment from a historical personal email. Restore via authorized administrator provisioning.

create table if not exists public.staff (
  id uuid primary key default gen_random_uuid(),
  name text not null unique check (char_length(name) between 1 and 40),
  color text not null default '#8FB7FF' check (color ~ '^#[0-9A-Fa-f]{6}$'),
  active boolean not null default true,
  created_at timestamptz not null default now()
);
alter table public.staff enable row level security;

create table if not exists public.duty_types (
  id bigint generated by default as identity primary key,
  code text not null unique,
  label text not null,
  group_name text not null check (group_name in ('值班','门诊')),
  color text not null default '#8FB7FF' check (color ~ '^#[0-9A-Fa-f]{6}$'),
  sort_order integer not null default 0,
  active boolean not null default true
);
alter table public.duty_types enable row level security;

create table if not exists public.schedule_assignments (
  id uuid primary key default gen_random_uuid(),
  work_date date not null,
  duty_type_id bigint not null references public.duty_types(id) on delete restrict,
  staff_id uuid not null references public.staff(id) on delete restrict,
  time_slot text not null default '未标注'
    check (time_slot in ('未标注','全天','上午','下午','夜间')),
  note text check (note is null or char_length(note) <= 100),
  created_at timestamptz not null default now(),
  unique(work_date,duty_type_id,staff_id,time_slot)
);
create index if not exists schedule_assignments_date_idx on public.schedule_assignments(work_date);
create index if not exists schedule_assignments_staff_idx on public.schedule_assignments(staff_id);
create index if not exists schedule_assignments_type_idx on public.schedule_assignments(duty_type_id);
alter table public.schedule_assignments enable row level security;

revoke all on table public.staff from anon, authenticated;
revoke all on table public.duty_types from anon, authenticated;
revoke all on table public.schedule_assignments from anon, authenticated;

grant select on public.staff, public.duty_types, public.schedule_assignments to authenticated;
grant insert(name,color,active) on public.staff to authenticated;
grant update(name,color,active) on public.staff to authenticated;
grant delete on public.staff to authenticated;
grant insert(code,label,group_name,color,sort_order,active) on public.duty_types to authenticated;
grant update(label,group_name,color,sort_order,active) on public.duty_types to authenticated;
grant delete on public.duty_types to authenticated;
grant insert(work_date,duty_type_id,staff_id,time_slot,note) on public.schedule_assignments to authenticated;
grant update(work_date,duty_type_id,staff_id,time_slot,note) on public.schedule_assignments to authenticated;
grant delete on public.schedule_assignments to authenticated;

drop policy if exists "authorized_read_staff" on public.staff;
create policy "authorized_read_staff" on public.staff for select to authenticated
using (public.current_member_id() is not null);
drop policy if exists "admin_write_staff_insert" on public.staff;
create policy "admin_write_staff_insert" on public.staff for insert to authenticated with check (public.is_admin());
drop policy if exists "admin_write_staff_update" on public.staff;
create policy "admin_write_staff_update" on public.staff for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin_write_staff_delete" on public.staff;
create policy "admin_write_staff_delete" on public.staff for delete to authenticated using (public.is_admin());

drop policy if exists "authorized_read_duty_types" on public.duty_types;
create policy "authorized_read_duty_types" on public.duty_types for select to authenticated
using (public.current_member_id() is not null);
drop policy if exists "admin_write_duty_types_insert" on public.duty_types;
create policy "admin_write_duty_types_insert" on public.duty_types for insert to authenticated with check (public.is_admin());
drop policy if exists "admin_write_duty_types_update" on public.duty_types;
create policy "admin_write_duty_types_update" on public.duty_types for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin_write_duty_types_delete" on public.duty_types;
create policy "admin_write_duty_types_delete" on public.duty_types for delete to authenticated using (public.is_admin());

drop policy if exists "authorized_read_schedule" on public.schedule_assignments;
create policy "authorized_read_schedule" on public.schedule_assignments for select to authenticated
using (public.current_member_id() is not null);
drop policy if exists "admin_write_schedule_insert" on public.schedule_assignments;
create policy "admin_write_schedule_insert" on public.schedule_assignments for insert to authenticated with check (public.is_admin());
drop policy if exists "admin_write_schedule_update" on public.schedule_assignments;
create policy "admin_write_schedule_update" on public.schedule_assignments for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin_write_schedule_delete" on public.schedule_assignments;
create policy "admin_write_schedule_delete" on public.schedule_assignments for delete to authenticated using (public.is_admin());

insert into public.duty_types(code,label,group_name,color,sort_order,active)
values
  ('duty','值班','值班','#FF8E95',10,true),
  ('primary','主班','值班','#C4A7FF',20,true),
  ('second','二线','值班','#81B7FF',30,true),
  ('follow','跟值','值班','#72D6B0',40,true),
  ('mobile_clinic','流动专家门诊','门诊','#F7C66B',50,true),
  ('specialty_1','专科门诊1','门诊','#F2A7C6',60,true),
  ('specialty_2','专科门诊2','门诊','#7ED7E9',70,true)
on conflict(code) do update set
  label=excluded.label,
  group_name=excluded.group_name,
  color=excluded.color,
  sort_order=excluded.sort_order,
  active=excluded.active;

-- OMITTED PRIVATE SEED: historical staff roster with real names. Recover data from encrypted backup, not public migrations.
